name: Build and Release

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake wget unzip

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
            yes | sdkmanager --install "ndk;29.0.14206865"
            echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
            echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/29.0.14206865" >> $GITHUB_ENV

      - name: Extract version from config.json
        id: version
        run: |
            MAJOR=$(jq -r '.majorVersion' config.json)
            MINOR=$(jq -r '.minorVersion' config.json)
            PATCH=$(jq -r '.patchVersion' config.json)
            VERSION="v${MAJOR}.${MINOR}.${PATCH}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Detected version: $VERSION"

      - name: Configure CMake with Ninja
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build with Ninja
        run: cmake --build build --parallel

      - name: List built artifacts
        run: ls -lah build || true

      - name: Upload .so artifact
        uses: actions/upload-artifact@v4
        with:
          name: libRobinHood
          path: build/libRobinHood*.so

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: libRobinHood
          path: build/

      - name: Extract version from config.json
        id: version
        run: |
          MAJOR=$(jq -r '.majorVersion' config.json)
          MINOR=$(jq -r '.minorVersion' config.json)
          PATCH=$(jq -r '.patchVersion' config.json)
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Create Git tag if missing
        run: |
          VERSION=${{ steps.version.outputs.version }}
          if ! git rev-parse "$VERSION" >/dev/null 2>&1; then
            git tag "$VERSION"
            git push origin "$VERSION"
            echo "Created and pushed tag $VERSION"
          else
            echo "Tag $VERSION already exists."
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "RobinHood ${{ steps.version.outputs.version }}"
          files: build/libRobinHood*.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
